# Generated by Django 3.0.6 on 2020-05-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
